import { exportAssetMap } from './asset-review';
import { Inventory, BuildOptions, BuildResult } from './types';
import { rgbaCss, round } from './util';

const cssName = (s: string) => s.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').toLowerCase();

function lineHeightCss(lh: LineHeight): string {
  if (lh.unit === 'AUTO') return 'normal';
  return lh.unit === 'PERCENT' ? `${round(lh.value / 100, 3)}` : `${round(lh.value)}px`;
}
function letterSpacingCss(ls: LetterSpacing): string {
  if (!ls.value) return '0';
  return ls.unit === 'PERCENT' ? `${round(ls.value / 100, 3)}em` : `${round(ls.value)}px`;
}

function setDeep(obj: Record<string, any>, path: string[], value: any) {
  let cur = obj;
  for (let i = 0; i < path.length - 1; i++) {
    cur[path[i]] = cur[path[i]] || {};
    cur = cur[path[i]];
  }
  cur[path[path.length - 1]] = value;
}

export function buildTokenFiles(inv: Inventory, opts: BuildOptions, result: Omit<BuildResult, 'files'>): Record<string, string> {
  const files: Record<string, string> = {};
  const generatedAt = new Date().toISOString();
  const source = { plugin: 'DS Foundry', version: '1.5.0', generatedAt, scope: inv.scope, pages: inv.pages };

  // -------- DTCG tokens.json --------
  const dtcg: Record<string, any> = { $schema: 'https://tr.designtokens.org/format/', $extensions: { 'com.cogspa.dsfoundry': source } };
  for (const c of inv.colors) {
    setDeep(dtcg, ['color', ...c.name.split('/')], { $type: 'color', $value: rgbaCss(c.r, c.g, c.b, c.a), $extensions: { usage: c.count } });
  }
  for (const s of inv.spacing) {
    setDeep(dtcg, ['space', String(s.value)], { $type: 'dimension', $value: `${s.value}px`, $extensions: { usage: s.count } });
  }
  for (const r of inv.radii) {
    setDeep(dtcg, ['radius', r.name.split('/')[1]], { $type: 'dimension', $value: r.value >= 999 ? '9999px' : `${r.value}px`, $extensions: { usage: r.count } });
  }
  for (const e of inv.effects) {
    const shadows = e.effects.filter((x) => x.type === 'DROP_SHADOW' || x.type === 'INNER_SHADOW') as (DropShadowEffect | InnerShadowEffect)[];
    if (shadows.length) {
      setDeep(dtcg, ['shadow', ...e.name.split('/')], {
        $type: 'shadow',
        $value: shadows.map((s) => ({
          color: rgbaCss(s.color.r, s.color.g, s.color.b, s.color.a),
          offsetX: `${round(s.offset.x)}px`, offsetY: `${round(s.offset.y)}px`,
          blur: `${round(s.radius)}px`, spread: `${round(s.spread || 0)}px`, inset: s.type === 'INNER_SHADOW',
        })),
        $extensions: { usage: e.count },
      });
    } else {
      setDeep(dtcg, ['blur', ...e.name.split('/')], { $type: 'dimension', $value: `${round('radius' in e.effects[0] ? e.effects[0].radius : 0)}px`, $extensions: { usage: e.count } });
    }
  }
  for (const t of inv.types) {
    setDeep(dtcg, ['typography', ...t.name.split('/')], {
      $type: 'typography',
      $value: {
        fontFamily: t.family, fontWeight: t.cssWeight, fontStyle: /italic|oblique/i.test(t.style) ? 'italic' : 'normal',
        fontSize: `${round(t.size)}px`, lineHeight: lineHeightCss(t.lineHeight), letterSpacing: letterSpacingCss(t.letterSpacing),
      },
      $extensions: { figmaStyle: t.style, usage: t.count },
    });
  }
  files['tokens.json'] = JSON.stringify(dtcg, null, 2);

  // -------- tokens.css --------
  const css: string[] = [`/* Generated by DS Foundry — ${generatedAt} */`, ':root {'];
  css.push('  /* colour */');
  for (const c of inv.colors) css.push(`  --color-${cssName(c.name)}: ${rgbaCss(c.r, c.g, c.b, c.a)};`);
  css.push('', '  /* spacing */');
  for (const s of inv.spacing) css.push(`  --space-${s.value}: ${s.value}px;`);
  css.push('', '  /* radius */');
  for (const r of inv.radii) css.push(`  --${cssName(r.name)}: ${r.value >= 999 ? '9999px' : r.value + 'px'};`);
  css.push('', '  /* effects */');
  for (const e of inv.effects) css.push(`  --${cssName(e.name)}: ${e.css};`);
  css.push('', '  /* typography */');
  for (const t of inv.types) {
    const n = cssName(t.name);
    css.push(`  --font-${n}: ${t.cssWeight} ${round(t.size)}px/${lineHeightCss(t.lineHeight)} "${t.family}", sans-serif;`);
    if (t.letterSpacing.value) css.push(`  --font-${n}-tracking: ${letterSpacingCss(t.letterSpacing)};`);
  }
  css.push('}', '');
  css.push('/* Utility classes for typography */');
  for (const t of inv.types) {
    const n = cssName(t.name);
    css.push(`.text-${n} { font: var(--font-${n});${t.letterSpacing.value ? ` letter-spacing: var(--font-${n}-tracking);` : ''} }`);
  }
  files['tokens.css'] = css.join('\n') + '\n';

  // -------- tailwind --------
  const tw: any = { theme: { extend: { colors: {}, spacing: {}, borderRadius: {}, boxShadow: {}, fontSize: {}, fontFamily: {} } } };
  for (const c of inv.colors) setDeep(tw.theme.extend.colors, c.name.split('/').map(cssName), rgbaCss(c.r, c.g, c.b, c.a));
  for (const s of inv.spacing) tw.theme.extend.spacing[String(s.value)] = `${s.value}px`;
  for (const r of inv.radii) tw.theme.extend.borderRadius[r.name.split('/')[1]] = r.value >= 999 ? '9999px' : `${r.value}px`;
  for (const e of inv.effects) if (e.name.startsWith('elevation')) tw.theme.extend.boxShadow[cssName(e.name)] = e.css;
  for (const t of inv.types) tw.theme.extend.fontSize[cssName(t.name)] = [`${round(t.size)}px`, { lineHeight: lineHeightCss(t.lineHeight), letterSpacing: letterSpacingCss(t.letterSpacing), fontWeight: String(t.cssWeight) }];
  const fams = [...new Set(inv.types.map((t) => t.family))];
  fams.forEach((f, i) => (tw.theme.extend.fontFamily[i === 0 ? 'sans' : cssName(f)] = [f, 'sans-serif']));
  files['tailwind.tokens.cjs'] = `/** Generated by DS Foundry — ${generatedAt}. Merge into tailwind.config.js */\nmodule.exports = ${JSON.stringify(tw, null, 2)};\n`;

  // -------- markdown doc --------
  const md: string[] = [];
  md.push(`# Design system — ${inv.pages.join(', ')}`);
  md.push('', `Generated by DS Foundry on ${generatedAt.slice(0, 10)} from ${inv.nodeCount.toLocaleString()} layers (${inv.scope}).`, '');
  md.push('## What was built', '');
  md.push(`- ${result.paintStyles} colour styles, ${result.textStyles} text styles, ${result.effectStyles} effect styles`);
  md.push(`- ${result.variables} variables in the "DS Foundry / Primitives" collection`);
  md.push(`- ${result.componentSets} component sets (${result.components} variants) and ${result.icons} icon components`);
  md.push(`- ${result.labeled} layers labelled with the \`${opts.prefix}\` prefix`);
  if (result.notes.length) { md.push('', '### Notes', ''); for (const n of result.notes) md.push(`- ${n}`); }
  md.push('', '## Colour', '', '| Token | Value | Uses |', '|---|---|---|');
  for (const c of inv.colors) md.push(`| \`${c.name}\` | \`${rgbaCss(c.r, c.g, c.b, c.a)}\` | ${c.count} |`);
  md.push('', '## Typography', '', '| Token | Font | Size | Line height | Tracking | Uses |', '|---|---|---|---|---|---|');
  for (const t of inv.types) md.push(`| \`${t.name}\` | ${t.family} ${t.style} | ${round(t.size)}px | ${lineHeightCss(t.lineHeight)} | ${letterSpacingCss(t.letterSpacing)} | ${t.count} |`);
  md.push('', '## Spacing', '', '| Token | Value | Uses |', '|---|---|---|');
  for (const s of inv.spacing) md.push(`| \`${s.name}\` | ${s.value}px | ${s.count} |`);
  md.push('', '## Radius', '', '| Token | Value | Uses |', '|---|---|---|');
  for (const r of inv.radii) md.push(`| \`${r.name}\` | ${r.value >= 999 ? 'full' : r.value + 'px'} | ${r.count} |`);
  md.push('', '## Effects', '', '| Token | CSS | Uses |', '|---|---|---|');
  for (const e of inv.effects) md.push(`| \`${e.name}\` | \`${e.css}\` | ${e.count} |`);
  md.push('', '## Elements found', '', '| Category | Count |', '|---|---|');
  const counts = new Map<string, number>();
  for (const e of inv.elements) counts.set(e.category, (counts.get(e.category) || 0) + 1);
  counts.set('icon', inv.icons.length);
  for (const [k, v] of [...counts.entries()].sort((a, b) => b[1] - a[1])) md.push(`| ${k} | ${v} |`);
  if (inv.components.length) {
    md.push('', '## Components already in use', '', '| Component | Instances | Source |', '|---|---|---|');
    for (const c of inv.components.slice(0, 80)) md.push(`| ${c.name} | ${c.count} | ${c.remote ? 'library' : 'local'} |`);
  }
  if (inv.missingFonts.length) md.push('', `> Missing fonts: ${inv.missingFonts.join(', ')} — text styles for these were skipped.`);
  files['DESIGN_SYSTEM.md'] = md.join('\n') + '\n';

  // -------- raw inventory --------
  files['inventory.json'] = JSON.stringify({
    source,
    elements: inv.elements.map((e) => ({ id: e.id, page: e.page, category: e.category, name: e.name, text: e.text, w: round(e.w), h: round(e.h), fillRole: e.fillRole, size: e.sizeClass, inInstance: e.inInstance })),
    icons: inv.icons.map((e) => ({ id: e.id, page: e.page, name: e.name, w: round(e.w), h: round(e.h) })),
    components: inv.components,
    fonts: inv.fonts,
  }, null, 2);

  if (inv.assetMap) files['asset-map.json'] = exportAssetMap(inv.assetMap);
  const canonical = new Map((inv.assetMap?.assets || []).flatMap(f=>f.variants.map(v=>[v.nodeId,{assetId:f.assetId,variantId:v.variantId,status:f.status}] as const)));
  files['layout-metadata.json'] = JSON.stringify({ schemaVersion: 1, elements: [...inv.elements,...inv.icons,...inv.shapes].map(r=>({nodeId:r.id,category:r.category,layout:r.layout,canonical:canonical.get(r.id)})) },null,2);
  files['asset-identities.json']=JSON.stringify({schemaVersion:1,assets:[...inv.elements,...inv.icons,...inv.shapes].filter(r=>r.assetName).map(r=>({nodeId:r.id,name:r.semanticName,kind:r.category,...r.assetName}))},null,2);
  files['artwork-parts.json']=JSON.stringify({schemaVersion:1,artwork:[...inv.elements,...inv.icons,...inv.shapes].filter(r=>r.artworkRole).map(r=>({nodeId:r.id,role:r.artworkRole,partOf:r.partOf})),parts:inv.artworkParts||[]},null,2);
  return files;
}
